
/*==============================================================*/
/* Table: degree                                                  */
/* degree_init.sql                                                */
/*==============================================================*/

INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'研究生','','00','YJS',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'研究生毕业','','01','YJSBY',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'相当研究生毕业','','02','XDYJSBY',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'研究生肄业','','09','YJSYY',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'大学本科','','10','DXBK',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'相当大学毕业','','18','XDDXBY',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'大学肄业','','19','DXYY',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'大学专科','','20','DXZK',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'专科毕业','','21','ZKBY',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'相当专科毕业','','28','XDZKBY',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'专科肄业','','29','ZKYY',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'中专或中技','','30','ZZHZJ',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'中专毕业','','31','ZZBY',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'中技毕业','','32','ZJBY',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'相当中专或中技','','33','XDZZHZJ',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'中专或中技肄业','','39','ZZHZJYY',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'技工学校','','40','JGXX',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'技工学校毕业','','41','JGXXBY',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'技工学校肄业','','49','JGXXYY',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'高中','','50','GZ',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'高中毕业','','51','GZBY',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'职高毕业','','52','ZGBY',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'农高毕业','','53','NGBY',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'相当高中毕业','','58','XDGZBY',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'高中肄业','','59','GZYY',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'初中','','60','CZ',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'初中毕业','','61','CZBY',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'职业初中','','62','ZYCZ',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'农业初中','','63','NYCZ',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'相当初中','','68','XDCZ',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'初中肄业','','69','CZYY',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'小学','','70','XX',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'小学毕业','','71','XXBY',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'相当小学','','78','XDXX',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'小学肄业','','79','XXYY',1,SYSDATE);
INSERT INTO DEGREE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'文盲','','80','WM',1,SYSDATE);
