
/*==============================================================*/
/* Table: province                                              */
/* province_init.sql                                            */
/*==============================================================*/

INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'北京市','','110000','BJS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'天津市','','120000','TJS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'河北省','','130000','HBS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'山西省','','140000','SXS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'内蒙古自治区','','150000','NMGZZQ',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'辽宁省','','210000','LNS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'吉林省','','220000','JLS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'黑龙江省','','230000','HLJS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'上海市','','310000','SHS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'江苏省','','320000','JSS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'浙江省','','330000','ZJS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'安徽省','','340000','AHS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'福建省','','350000','FJS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'江西省','','360000','JXS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'山东省','','370000','SDS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'河南省','','410000','HNS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'湖北省','','420000','HBS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'湖南省','','430000','HNS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'广东省','','440000','GDS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'广西壮族自治区','','450000','GXZZZZQ',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'海南省','','460000','HNS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'重庆市','','500000','CQS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'四川省','','510000','SCS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'贵州省','','520000','GZS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'云南省','','530000','YNS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'西藏自治区','','540000','XZZZQ',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'陕西省','','610000','SXS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'甘肃省','','620000','GSS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'青海省','','630000','QHS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'宁夏回族自治区','','640000','NXHZZZQ',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'新疆维吾尔自治区','','650000','XJWWEZZQ',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'台湾省','','710000','TWS',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'香港特别行政区','','810000','XGTBXZQ',1,SYSDATE);
INSERT INTO PROVINCE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'澳门特别行政区','','820000','AMTBXZQ',1,SYSDATE);