
/*==============================================================*/
/* Table: race                                                  */
/* race_init.sql                                                */
/*==============================================================*/

INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'汉族','','01','HZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'蒙古族','','02','MGZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'回族','','03','HZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'藏族','','04','ZZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'维吾尔族','','05','WWEZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'苗族','','06','MZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'彝族','','07','YZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'壮族','','08','ZZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'布依族','','09','BYZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'朝鲜族','','10','CXZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'满族','','11','MZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'侗族','','12','DZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'瑶族','','13','YZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'白族','','14','BZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'土家族','','15','TJZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'哈尼族','','16','HNZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'哈萨克族','','17','HSKZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'傣族','','18','DZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'黎族','','19','LZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'傈僳族','','20','LSZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'佤族','','21','WZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'畲族','','22','SZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'高山族','','23','GSZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'拉祜族','','24','LHZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'水族','','25','SZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'东乡族','','26','DXZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'纳西族','','27','NXZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'景颇族','','28','JPZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'柯尔克孜族','','29','KEKZZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'土族','','30','TZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'达翰尔族','','31','DHEZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'么佬族','','32','MLZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'羌族','','33','QZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'布朗族','','34','BLZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'撒拉族','','35','SLZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'毛难族','','36','MNZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'仡佬族','','37','GLZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'锡伯族','','38','XBZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'阿昌族','','39','ACZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'普米族','','40','PMZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'塔吉克族','','41','TJKZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'怒族','','42','NZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'乌孜别克族','','43','WZBKZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'俄罗斯族','','44','ELSZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'鄂温克族','','45','EWKZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'崩龙族','','46','BLZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'保安族','','47','BAZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'裕固族','','48','YGZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'京族','','49','JZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'塔塔尔族','','50','TTEZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'独龙族','','51','DLZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'鄂伦春族','','52','ELCZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'赫哲族','','53','HZZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'门巴族','','54','MBZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'珞巴族','','55','LBZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'基诺族','','56','JNZ',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'其它','','97','QT',1,SYSDATE);
INSERT INTO RACE(ID,NAME,ROME,SZ_CODE,ZM_CODE,STATE,VERSION) VALUES((select SYS_guid()from dual),'外国血统','','98','WGXT',1,SYSDATE);